spring.application.name=dbin
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=RM559603
spring.datasource.password=220897
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# FLYWAY
spring.flyway.enabled=true
spring.flyway.baselineOnMigrate=false
spring.flyway.schemas=RM559603
spring.flyway.locations=classpath:db/migration
spring.flyway.table=FLYWAY_HISTORY

# HIBERNATE
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=RM559603

# BASIC AUTH
spring.security.user.name=admin
spring.security.user.password=a99983b6-48f6-4bda-8e1a-4ca7024780e2
spring.security.user.roles=USER

# LOGS
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.flywaydb=DEBUG

# SWAGGER / OPENAPI
springdoc.swagger-ui.path=/swagger-ui.html

